 const typewriter = new Typewriter('#typewriter', {
                        delay: 0,
                        deleteSpeed: 0,
                        });

                        typewriter.callFunction((state) => {
                                 // hide cursor
                                 state.elements.cursor.style.display = 'none'
                        })
                        typewriter.typeString('"Oigan, chicas, ¿alguna ha visto a Melody hoy?"')
                            typewriter.pauseFor(5000)
                            .deleteAll(0)
                            .typeString('"¿Eh? ¿Qué te pasa con ella ahora?"')
                            .pauseFor(4000)
                            .deleteAll(0)
                            .typeString('"Es solo que no se ha aparecido por las prácticas estos días... ¿Se habrá enfermado?"')
                            .pauseFor(7000)
                            .deleteAll(0)
                            .typeString('"A saber. No me importa."')
                            .pauseFor(2500)
                            .deleteAll(0)
                            .typeString('"Buenas tardes, chicas. Melody no está enferma, pero ya no está cursando aquí."')
                            .pauseFor(7000)
                            .deleteAll(0)
                            .typeString('<b>"¡¿QUÉ!?"</b>')
                            .pauseFor(2000)
                            .deleteAll(0)
                            .typeString('"Profesora, ¿desde cuándo ha sido eso?"')
                            .pauseFor(4000)
                            .deleteAll(0)
                            .typeString('"La semana pasada. Sus padres han hecho todo el trámite para Grecia."')
                            .pauseFor(6000)
                            .deleteAll(0)
                            .typeString('"Esa estúpida... Además de mala compañera, nos deja plantadas para irse a vivir la vida."')
                            .pauseFor(7000)
                            .deleteAll(0)
                            .typeString('"Bueno, cada quien tiene su camino. De seguro se pueden comunicar con ella para hablarle. Nos vemos en clase."')
                            .pauseFor(8000)
                            .deleteAll(0)
                            .typeString('"Pero ni siquiera tenemos su número... <i>sniff</i>"')
                            .pauseFor(4000)
                            .deleteAll(0)
                            .typeString('"Entonces su hermano sabrá algo más, ¿no?"')
                            .pauseFor(4000)
                            .deleteAll(0)
                            .typeString('"Quizás..."')
                            .pauseFor(2000)
                            .deleteAll(0)
                            .typeString('"¡Hmph! Me cansé de oír su nombre. Soluciónenlo por su cuenta, que me voy."')
                            .pauseFor(6000)
                            .deleteAll(0)
                            .changeDelay(100)
                            .typeString('<i>Primero Aria, y ahora ella se va también... ¿Por qué esas dos son tan estúpidas?<i>')
                            .start();